# Configuracion de SonarCloud para este proyecto.
# Reemplaza los dos valores de abajo con los que te muestre SonarCloud
# al crear el proyecto (ver guia de configuracion).

sonar.organization=Yampola_registro-donantes-chocomida
sonar.projectKey=63e4973b6af2248bc414051ee09f6e7de01a4a3f

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
