# Configuracion de SonarCloud para este proyecto.
# Reemplaza los dos valores de abajo con los que te muestre SonarCloud
# al crear el proyecto (ver guia de configuracion).

sonar.organization=Yampola
sonar.projectKey=Yampola_registro-donantes-chocomida

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11
